name: Build and Push Container images

env:
  IMAGE_BASE_NAME: quay.io/rhappsvcs/spring-to-quarkus-mta-cli
  MTA_VERSION: 6.1.7.Final
  LATEST_IMAGE_TAG: latest

on:
  workflow_dispatch:
  
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.workflow_run.head_branch || github.event.ref || github.ref }}"
  cancel-in-progress: false

jobs:
  build-push-images:
    if: (github.event_name == 'workflow_dispatch') && (github.repository == 'RedHat-Middleware-Workshops/spring-to-quarkus-mta-cli')
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REPO_USERNAME }}
          password: ${{ secrets.QUAY_REPO_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          load: false
	  tags: ${{ env.IMAGE_BASE_NAME }}:${{ env.MTA_VERSION }}
          #tags: ${{ env.IMAGE_BASE_NAME }}:${{ env.MTA_VERSION }},${{ env.IMAGE_BASE_NAME }}:${{ env.LATEST_IMAGE_TAG }}
